# Generated by Django 4.2.16 on 2024-09-24 06:12

from django.db import migrations, models

def populate_icon_classes(apps):
    Category = apps.get_model('product', 'Category')

    icons = {
        'Clothing': 'fa-solid fa-shirt',
        'Electronics': 'fa-solid fa-laptop',
        'Furniture': 'fa-solid fa-couch',
    }

    for name, icon_class in icons.items():
        try:
            category = Category.objects.get(name=name)
            category.icon_class = icon_class
            category.save()
        except Category.DoesNotExist:
            continue


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_options_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(populate_icon_classes),
    ]
