# Generated by Django 4.2.16 on 2024-09-19 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_alter_category_options_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of', models.DateTimeField(auto_now_add=True)),
                ('status', models.DateTimeField(auto_now=True)),
                ('messengers', models.ManyToManyField(related_name='dialogues', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='product.product')),
            ],
            options={
                'ordering': ('-status',),
            },
        ),
        migrations.CreateModel(
            name='DialogueText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_of', models.DateTimeField(auto_now_add=True)),
                ('created_dialogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_dm', to=settings.AUTH_USER_MODEL)),
                ('dialogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_messages', to='dialogue.dialogue')),
            ],
        ),
    ]
